<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Adminhtml\Order\Totals\Tax */
?>
<?php
/** @var $_source \Magento\Sales\Model\Order\Invoice */
$_source    = $block->getSource();
$_order     = $block->getOrder();
$orderDate = $_order->getCreatedAt();
/**
 *
 * @var $_gstHelper \Codilar\Gst\Helper\Data
 */
$_gstHelper = $this->helper('Codilar\Gst\Helper\Data');
$productionState = $_gstHelper->getProductionState();
$shippingGstStatus = $_gstHelper->getShippingGstStatus();
$productionState = str_replace(' ', '', strtolower($productionState));
$orderDate = $_order->getCreatedAt();
$orderDate = date_create($orderDate);
$date = "2017-06-30 11:59:59";
$gstDate=date_create($date);
$gstOrderStatus = false;
if($gstDate < $orderDate){
    $gstOrderStatus = true;
}
$state = $_order->getShippingAddress()->getRegion();
$state = str_replace(' ', '', strtolower($state));
$shippingBaseTaxAmount = $_order->getBaseShippingTaxAmount();
$totalBaseGst = $_source->getBaseTaxAmount();
$baseSgst = $totalBaseGst/2;
$baseIgst = $totalBaseGst;
$totalGst = $_source->getTaxAmount();
$shippingTaxAmount = $_order->getShippingTaxAmount();
$totalGst = $_source->getTaxAmount();
$sgst = $totalGst/2;
$igst = $totalGst;

$_fullInfo  = $block->getFullTaxInfo();
?>

<?php if ($block->displayFullSummary()): ?>
    <?php $isTop = 1; ?>
    <?php if (isset($_fullInfo[0]['rates'])): ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php if (isset($info['hidden']) && $info['hidden']) {
    continue;
} ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['amount'];
                $baseAmount = $info['base_amount'];
                $rates      = $info['rates'];
                $isFirst    = 1;
            ?>

            <?php foreach ($rates as $rate): ?>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <?php if (!is_null($rate['percent'])): ?>
                    <td class="label"><?php /* @escapeNotVerified */ echo $rate['title']; ?> (<?php echo (float)$rate['percent']; ?>%)<br /></td>
                <?php else: ?>
                    <td class="label"><?php /* @escapeNotVerified */ echo $rate['title']; ?><br /></td>
                <?php endif; ?>
                <?php if ($isFirst): ?>
                    <td rowspan="<?php echo count($rates); ?>"><?php /* @escapeNotVerified */ echo $block->displayAmount($amount, $baseAmount); ?></td>
                <?php endif; ?>
            </tr>
            <?php
                $isFirst = 0;
                $isTop = 0;
            ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $isFirst    = 1;
            ?>

            <?php
                $isFirst = 0;
                $isTop = 0;
            ?>
        <?php endforeach; ?>
        <?php
        if(($state==$productionState) && $gstOrderStatus){
            $state_title = "SGST";
            $central_title = "CGST";
            ?>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="label"><?php echo $block->escapeHtml("SGST"); ?><br /></td>
                <td><?php /* @escapeNotVerified */ echo $block->displayAmount($sgst, $baseSgst); ?></td>
            </tr>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="label"><?php echo $block->escapeHtml("CGST"); ?><br /></td>
                <td><?php /* @escapeNotVerified */ echo $block->displayAmount($sgst, $baseSgst); ?></td>
            </tr>
            <?php
        }
        else if($gstOrderStatus){
            $title = "IGST";
            ?>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="label"><?php echo $block->escapeHtml("IGST"); ?><br /></td>
                <td><?php /* @escapeNotVerified */ echo $block->displayAmount($igst, $baseIgst); ?></td>
            </tr>
            <?php
        }
        else{
            ?>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="label"><?php echo $block->escapeHtml("Tax Amount"); ?><br /></td>
                <td><?php /* @escapeNotVerified */ echo $block->displayAmount($igst, $baseIgst); ?></td>
            </tr>
            <?php
        }
        ?>
        <?php if($shippingGstStatus && $shippingTaxAmount > 0): ?>
            <tr class="summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="label"><?php echo $block->escapeHtml("Shipping GST"); ?><br /></td>
                <td><?php /* @escapeNotVerified */ echo $block->displayAmount($shippingTaxAmount, $shippingBaseTaxAmount); ?></td>
            </tr>
        <?php endif; ?>
    <?php endif; ?>
<?php endif;?>
<?php if ($block->displayFullSummary() && $_fullInfo): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details')">
<?php else: ?>
<tr>
<?php endif; ?>
    <td class="label">
        <div class="summary-collapse">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary()): ?>
            <?php /* @escapeNotVerified */ echo __('Total GST') ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo __('Total GST') ?>
        <?php endif;?>
        </div>
    </td>
    <td>
        <?php /* @escapeNotVerified */ echo $block->displayAmount($totalGst, $totalBaseGst); ?>
    </td>
</tr>

