<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php
/**
 *
 * @var $_gstHelper \Codilar\Gst\Helper\Data
 */
$_gstHelper = $this->helper('Codilar\Gst\Helper\Data');
$productionState = $_gstHelper->getProductionState();
$moduleStatus = $_gstHelper->getModuleStatus();
$_item = $block->getItem();
$_order = $block->getOrder();
$productionState = str_replace(' ', '', strtolower($productionState));
$orderDate = $_order->getCreatedAt();
$orderDate = date_create($orderDate);
$date = "2017-06-30 11:59:59";
$gstDate=date_create($date);
$gstOrderStatus = false;
if($gstDate < $orderDate){
    $gstOrderStatus = true;
}
$state = $_order->getShippingAddress()->getRegion();
$state = str_replace(' ', '', strtolower($state));

$productData = $_gstHelper->getProductById($_item->getProductId());
$productHsn = $productData->getHsn();
?>
<?php $block->setPriceDataObject($_item); ?>
<tr>
    <td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
    <?php if($moduleStatus): ?>
        <td class="col-hsn"><?php echo $productHsn; ?></td>
    <?php endif; ?>
    <td class="col-price">
        <?php echo $block->getColumnHtml($_item, 'price'); ?>
    </td>
    <td class="col-ordered-qty"><?php echo $block->getColumnHtml($_item, 'qty') ?></td>
    <?php if ($block->canParentReturnToStock($_item)) : ?>
        <td class="col-return-to-stock">
            <?php if ($block->canReturnItemToStock($_item)) : ?>
                <input type="checkbox"
                       class="admin__control-checkbox"
                       name="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>][back_to_stock]"
                       value="1"<?php if ($_item->getBackToStock()):?> checked<?php endif;?>/>
                <label class="admin__field-label"></label>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col-refund col-qty">
        <?php if ($block->canEditQty()) : ?>
            <input type="text"
                   class="input-text admin__control-text qty-input"
                   name="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>][qty]"
                   value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>"/>
        <?php else : ?>
            <?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <td class="col-subtotal">
        <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <?php if(($state==$productionState) && $gstOrderStatus && $moduleStatus):
        $originalTaxAmount = $_item->getTaxAmount();
        $taxAmount = $originalTaxAmount / 2;
        $_item->setTaxAmount($taxAmount);?>
        <td class="col-sgst"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
        <td class="col-cgst"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
        <?php $_item->setTaxAmount($originalTaxAmount); ?>
    <?php elseif($gstOrderStatus && $moduleStatus): ?>
        <td class="col-igst"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
    <?php else: ?>
        <td class="col-tax"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
    <?php endif; ?>
    <td class="col-discont"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $block->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
