<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_order = $block->getOrder();
/**
 *
 * @var $_gstHelper \Codilar\Gst\Helper\Data
 */
$_gstHelper = $this->helper('Codilar\Gst\Helper\Data');
$productionState = $_gstHelper->getProductionState();
$moduleStatus = $_gstHelper->getModuleStatus();
$productionState = str_replace(' ', '', strtolower($productionState));
$orderDate = $_order->getCreatedAt();
$orderDate = date_create($orderDate);
$date = "2017-06-30 11:59:59";
$gstDate=date_create($date);
$gstOrderStatus = false;
if($gstDate < $orderDate){
    $gstOrderStatus = true;
}
$state = $_order->getShippingAddress()->getRegion();
$state = str_replace(' ', '', strtolower($state));
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-invoice-tables">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
            <?php if($moduleStatus): ?>
                <th class="col-hsn"><span><?php /* @escapeNotVerified */ echo __('HSN') ?></span></th>
            <?php endif; ?>
            <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
            <th class="col-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
            <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
            <?php if(($state==$productionState) && $gstOrderStatus && $moduleStatus): ?>
                <th class="col-sgst"><span><?php /* @escapeNotVerified */ echo __('SGST') ?></span></th>
                <th class="col-cgst"><span><?php /* @escapeNotVerified */ echo __('CGST') ?></span></th>
            <?php elseif($gstOrderStatus && $moduleStatus): ?>
                <th class="col-igst"><span><?php /* @escapeNotVerified */ echo __('IGST') ?></span></th>
            <?php elseif($moduleStatus): ?>
                <th class="col-tax"><span><?php /* @escapeNotVerified */ echo __('GST Amount') ?></span></th>
            <?php else: ?>
                <th class="col-tax"><span><?php /* @escapeNotVerified */ echo __('Tax Amount') ?></span></th>
            <?php endif; ?>
            <th class="col-discount"><span><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></span></th>
            <th class="col-total last"><span><?php /* @escapeNotVerified */ echo __('Row Total') ?></span></th>
        </tr>
        </thead>
        <?php
        $_items = $block->getInvoice()->getAllItems() ?>
        <?php $i = 0; foreach ($_items as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()) {
                continue;
            } else {
                $i++;
            } ?>
            <tbody class="<?php /* @escapeNotVerified */ echo $i%2 ? 'even' : 'odd' ?>">
            <?php echo $block->getItemHtml($_item) ?>
            <?php echo $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
